FROM {IMAGE_FROM}

MAINTAINER Jonathan A. Schweder "jonathanschweder@gmail.com"

WORKDIR /usr/src

RUN wget "https://getcomposer.org/composer.phar" \
    && mv ./composer.phar /usr/local/bin/composer \
    && chmod a+x /usr/local/bin/composer \
    && composer global require jaschweder/tools:^1.8 \
    && composer global require "hirak/prestissimo:^0.3"

ENV PATH "$PATH:/root/.composer/vendor/bin"

WORKDIR /var/www

CMD ["composer", "--version"]
