FROM {IMAGE_FROM}

MAINTAINER Jonathan A. Schweder "jonathanschweder@gmail.com"

############################################################################
#                                   Nginx                                  #
############################################################################

COPY ./nginx-vh-default /etc/nginx/sites-available/default
