FROM {IMAGE_FROM}

MAINTAINER Jonathan A. Schweder "jonathanschweder@gmail.com"

RUN composer global require phpstan/phpstan

COPY ./generate_metrics /usr/local/bin/generate_metrics

CMD ["generate_metrics", "/var/www"]
